- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: création du compte pour Wildfly
  user:
    name: wildfly
    shell: /bin/false
    system: yes
    home: '{{wildfly_home}}'

- name: installation de Wildfly
  unarchive:
    src: '{{wildfly_url}}'
    dest: '{{wildfly_home}}'
    remote_src: True
    extra_opts: "--strip-components=1"
    creates: '{{wildfly_home}}/bin/domain.sh'
    group: wildfly
    owner: wildfly

- name: création des répertoires
  file:
    path: '/etc/wildfly'
    state: directory
    owner: root
    group: root

- name: création fichier pour installation du service
  copy:
    src: '{{wildfly_home}}/docs/contrib/scripts/systemd/wildfly.conf'
    dest: '/etc/wildfly/wildfly.conf'
    remote_src: true
  notify:
    - activer Wildfly

- name: création fichier pour installation du service
  copy:
    src: '{{wildfly_home}}/docs/contrib/scripts/systemd/wildfly.service'
    dest: '/etc/systemd/system/wildfly.service'
    remote_src: true
  notify:
    - activer Wildfly

- name: création fichier pour installation du service
  copy:
    src: '{{wildfly_home}}/docs/contrib/scripts/systemd/launch.sh'
    dest: '{{wildfly_home}}/bin/launch.sh'
    remote_src: true
    mode: 'a+x'
    owner: wildfly
    group: wildfly
  notify:
    - activer Wildfly

- name: vérifier que Wildfly est actif
  service: state=started name=wildfly
